name: Docker

on:
  push:
      # Publish `master` as Docker `latest` image.
      branches:
        - master
        - develop
        - feature/**
      # Publish `v1.2.3` tags as releases.
      tags:
        - v*
env:
  IMAGE_NAME: live-data-service
  IMAGE_ID: sensateiot/live-data-service
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  BASE_PATH: SensateIoT.Platform/SensateIoT.Platform.Network/SensateIoT.Platform.Network.LiveDataService

jobs:
  push-livedataservice:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build SensateIoT.Platform/SensateIoT.Platform.Network --file $BASE_PATH/Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Get assembly version
        run: |
          PROJ=$BASE_PATH/package.json
          VERSION=$(pwsh -command "Scripts/Deployment/Get-PackageVersion.ps1 $PROJ")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check DockerHub
        run: |
          DOCKERTAG=$(pwsh -command "Scripts/Deployment/Check-DockerTag.ps1 $IMAGE_ID $VERSION")
          echo "TAG=$DOCKERTAG" >> $GITHUB_ENV

      - name: Push staging image
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          docker tag $IMAGE_NAME $IMAGE_ID:staging
          docker push $IMAGE_ID:staging
   
      - name: Push image
        if: ${{ env.TAG != 'exists' && github.ref == 'refs/heads/feature/network' }}
        run: |
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && docker push $IMAGE_ID:$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
